language: node_js

sudo: required

node_js:
  - 7

services:
  - docker

install: true

script:
  - docker login --username=ksh.max.spam@gmail.com --password=$(echo $API_KEY) registry.heroku.com
  - docker build -t registry.heroku.com/the-last-siege/web .
  - docker push registry.heroku.com/the-last-siege/web

